language: python
sudo: false

python:
  - 3.7-dev

# install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - git checkout master

script:
  - python 3dsdb.py 

after_success:
  - git config --global user.email "pokemonemerald0@gmail.com" 
  - git config --global user.name "hax0kartik"
  - git add -A
  - git commit -m "[Commit from Travis] New titles added [skip ci]" 
  - git remote rm origin
  - git remote add origin https://hax0kartik:$GITHUB_API_KEY@github.com/hax0kartik/3dsdb.git
  - git push origin master
  - echo "Done."